In [167]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Pandy', 'Bamboo', 'Fuzzy'],
    'Age': [5, 7, 4],
    'Bamboo_sticks' : [15, 6, 6]
}
df = pd.DataFrame(data)

In [168]:
print(df)

     Name  Age  Bamboo_sticks
0   Pandy    5             15
1  Bamboo    7              6
2   Fuzzy    4              6

In [169]:
df.head()

     Name  Age  Bamboo_sticks
0   Pandy    5             15
1  Bamboo    7              6
2   Fuzzy    4              6

In [170]:
df[df['Age']<6]   # df e filtering , filtering on a colums with a logic # df =df[df['Age']<6]

    Name  Age  Bamboo_sticks
0  Pandy    5             15
2  Fuzzy    4              6

In [171]:
df['Job'] = ['Intern', 'Manger', 'Intern']  #np.nan
print(df)

     Name  Age  Bamboo_sticks     Job
0   Pandy    5             15  Intern
1  Bamboo    7              6  Manger
2   Fuzzy    4              6  Intern

In [172]:
df.loc[df['Name']=='Pandy', 'Age'] = 6

In [173]:
df

     Name  Age  Bamboo_sticks     Job
0   Pandy    6             15  Intern
1  Bamboo    7              6  Manger
2   Fuzzy    4              6  Intern

In [174]:
df = df.drop('Bamboo_sticks', axis=1)

In [175]:
df

     Name  Age     Job
0   Pandy    6  Intern
1  Bamboo    7  Manger
2   Fuzzy    4  Intern

In [176]:
df = df.drop(['Age','Job' ], axis=1)

In [177]:
df

     Name
0   Pandy
1  Bamboo
2   Fuzzy

In [178]:
df.iloc[:3] #row [0]

     Name
0   Pandy
1  Bamboo
2   Fuzzy

In [179]:
df['Age']

KeyError: 'Age'

In [ ]:
df.iloc[0:2, 0:2]

     Name
0   Pandy
1  Bamboo

In [ ]:
df.iloc[0:2, 1:3]

Empty DataFrame
Columns: []
Index: [0, 1]

In [ ]:
df = pd.DataFrame({
    'Name': ['Pandy', 'Bamboo', 'Fuzzy', 'Fluffy'],
    'Age': [5,7,4,6],
    'Bamboo_Stickes': [33,55,66,77]
},index = ['a','b','c','d'])

In [ ]:
df

     Name  Age  Bamboo_Stickes
a   Pandy    5              33
b  Bamboo    7              55
c   Fuzzy    4              66
d  Fluffy    6              77

In [ ]:
df.loc['b']

Name              Bamboo
Age                    7
Bamboo_Stickes        55
Name: b, dtype: object

In [ ]:
df.loc[['a','c'], ['Name', 'Age']]

    Name  Age
a  Pandy    5
c  Fuzzy    4

In [ ]:
df_json = pd.read_json('test.json' )

In [ ]:
df_json.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406